# Netlify Configuration
[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/admin.html"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/instructor.html"
  to = "/instructor.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"